# ArgoCD Helm Chart Values
# Reference: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

# ArgoCD Server Configuration
server:

  # Command line parameters
  extraArgs:
    - --insecure

  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.lan
    paths:
      - /
    pathType: Prefix
    tls: false

  metrics:
    enabled: true

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true

# Dex Configuration
dex:
  enabled: false

# Repo polling interval (authenticated = 5000 req/hr limit, 10s = 360 req/hr)
configs:
  cm:
    timeout.reconciliation: 10s

# Global configuration
global:
  domain: argocd.lan
